version: '3.9'

networks:
  operational:
    external: true

volumes:
  esmaster1:
    driver: local
  esmaster2:
    driver: local
  esmaster3:
    driver: local
  logstash:
    driver: local
  kibanadata:
    driver: local
  filebeatdata:
    driver: local

configs:
  jvm-options-master:
    name: jvm-options-master-v1
    file: elasticsearch/jvm.master.options
  logstash-config:
    name: logstash-config-v4
    file: logstash/logstash.yml
  logstash-pipeline-config:
    name: logstash-pipeline-config-v9
    file: logstash/logstash.conf
  logstash-pipelines:
    name: logstash-pipelines-v1
    file: logstash/pipelines.yml
  filebeat:
    name: filebeat-config-v15
    file: filebeats/filebeat.yml

secrets:
  elastic-master1-certificate:
    external: true
  elastic-master1-key:
    external: true
  elastic-master2-certificate:
    external: true
  elastic-master2-key:
    external: true
  elastic-master3-certificate:
    external: true
  elastic-master3-key:
    external: true
  elastic-ca-certificate:
    external: true
  elastic-ca-key:
    external: true
  logstash-certificate:
    external: true

x-templates:
  replicated-deploy: &replicated
    logging:
      options:
        max-size: 20m
        max-file: 5
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ulimits:
      memlock: -1
      nofile:
        hard: 65536
        soft: 65536
      nproc: 65538

  elastic: &elastic-deployment-common
    <<: *replicated
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_STACK_VERSION}
    configs:
      - source: jvm-options-master
        target: /usr/share/elasticsearch/config/jvm.options
    logging:
      options:
        max-size: 20m
        max-file: 5
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints: [ node.role == worker ]

  master-environments: &environments
    cluster.name: "elastic-cluster"
    ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
    bootstrap.memory_lock: "true"
    action.destructive_requires_name: "true"
    xpack.license.self_generated.type: basic
    xpack.security.enabled: "true"
    xpack.security.http.ssl.enabled: "true"
    xpack.security.transport.ssl.enabled: "true"
    xpack.security.transport.ssl.verification_mode: "certificate"


services:

  kibana-password-initializer:
    image: alpine/curl:latest
    networks:
      - operational
    secrets:
      - source: elastic-ca-certificate
        target: /var/tmp/ca.crt
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      KIBANA_PASSWORD: ${KIBANA_PASSWORD}
    command: >
      -S -X POST --cacert /var/tmp/ca.crt --user "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" https://master1.elastic:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}"
    logging:
      options:
        max-size: 20m
        max-file: 5
    deploy:
      placement:
        constraints: [ node.role == worker ]
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none

  master1:
    <<: *elastic-deployment-common
    networks:
      operational:
        aliases:
          - master1.elastic
    volumes:
      - esmaster1:/usr/share/elasticsearch/data
    secrets:
      - source: elastic-master1-key
        target: /usr/share/elasticsearch/config/certs/master1.key
      - source: elastic-master1-certificate
        target: /usr/share/elasticsearch/config/certs/master1.crt
      - source: elastic-ca-certificate
        target: /usr/share/elasticsearch/config/certs/ca/ca.crt
    environment:
      <<: *environments
      node.name: es-master1
      discovery.seed_hosts: master2.elastic, master3.elastic
      cluster.initial_master_nodes: es-master1, es-master2, es-master3
      network.publish_host: master1.elastic
      xpack.security.http.ssl.key: /usr/share/elasticsearch/config/certs/master1.key
      xpack.security.http.ssl.certificate: /usr/share/elasticsearch/config/certs/master1.crt
      xpack.security.http.ssl.certificate_authorities: /usr/share/elasticsearch/config/certs/ca/ca.crt
      xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/certs/master1.key
      xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/certs/master1.crt
      xpack.security.transport.ssl.certificate_authorities: /usr/share/elasticsearch/config/certs/ca/ca.crt


  master2:
    <<: *elastic-deployment-common
    networks:
      operational:
        aliases:
          - master2.elastic
    secrets:
      - source: elastic-master2-key
        target: /usr/share/elasticsearch/config/certs/master2.key
      - source: elastic-master2-certificate
        target: /usr/share/elasticsearch/config/certs/master2.crt
      - source: elastic-ca-certificate
        target: /usr/share/elasticsearch/config/certs/ca/ca.crt
    volumes:
      - esmaster2:/usr/share/elasticsearch/data
    environment:
      <<: *environments
      node.name: es-master2
      discovery.seed_hosts: master1.elastic, master3.elastic
      cluster.initial_master_nodes: es-master1, es-master2, es-master3
      network.publish_host: master2.elastic
      xpack.security.http.ssl.key: /usr/share/elasticsearch/config/certs/master2.key
      xpack.security.http.ssl.certificate: /usr/share/elasticsearch/config/certs/master2.crt
      xpack.security.http.ssl.certificate_authorities: /usr/share/elasticsearch/config/certs/ca/ca.crt
      xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/certs/master2.key
      xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/certs/master2.crt
      xpack.security.transport.ssl.certificate_authorities: /usr/share/elasticsearch/config/certs/ca/ca.crt

  master3:
    <<: *elastic-deployment-common
    networks:
      operational:
        aliases:
          - master3.elastic
    secrets:
      - source: elastic-master3-key
        target: /usr/share/elasticsearch/config/certs/master3.key
      - source: elastic-master3-certificate
        target: /usr/share/elasticsearch/config/certs/master3.crt
      - source: elastic-ca-certificate
        target: /usr/share/elasticsearch/config/certs/ca/ca.crt
    volumes:
      - esmaster3:/usr/share/elasticsearch/data
    environment:
      <<: *environments
      node.name: es-master3
      discovery.seed_hosts: master1.elastic, master2.elastic
      cluster.initial_master_nodes: es-master1, es-master2, es-master3
      network.publish_host: master3.elastic
      xpack.security.http.ssl.key: /usr/share/elasticsearch/config/certs/master3.key
      xpack.security.http.ssl.certificate: /usr/share/elasticsearch/config/certs/master3.crt
      xpack.security.http.ssl.certificate_authorities: /usr/share/elasticsearch/config/certs/ca/ca.crt
      xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/certs/master3.key
      xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/certs/master3.crt
      xpack.security.transport.ssl.certificate_authorities: /usr/share/elasticsearch/config/certs/ca/ca.crt

  kibana:
    <<: *replicated
    image: docker.elastic.co/kibana/kibana:${ELASTIC_STACK_VERSION}
    networks:
      operational:
        aliases:
          - kibana.elastic
    secrets:
      - source: elastic-ca-certificate
        target: /usr/share/elasticsearch/config/certs/ca/ca.crt
    volumes:
      - kibanadata:/usr/share/kibana/data
    environment:
      SERVER_NAME: BookkMeKibana
      SERVER_PUBLICBASEURL: https://kibana.bookkme.app
      ELASTICSEARCH_HOSTS: '["https://master1.elastic:9200","https://master2.elastic:9200","https://master3.elastic:9200"]'
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD}
      XPACK_SECURITY_ENCRYPTIONKEY: ${KIBANA_ENCRYPTION_KEY}
      XPACK_SECURITY_ENABLED: "true"
      ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: /usr/share/elasticsearch/config/certs/ca/ca.crt
      XPACK_REPORTING_ENCRYPTIONKEY: ${KIBANA_ENCRYPTION_KEY}
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: ${KIBANA_ENCRYPTION_KEY}
    deploy:
      placement:
        constraints: [node.role == manager]

  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELASTIC_STACK_VERSION}
    command: ["filebeat", "-e", "--strict.perms=false"]
    user: root
    configs:
      - source: filebeat
        target: /usr/share/filebeat/filebeat.yml
    networks:
      - operational
    volumes:
      - filebeatdata:/usr/share/filebeat/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    ulimits:
      memlock:
        soft: -1
        hard: -1
    logging:
      options:
        max-size: 20m
        max-file: 5
    deploy:
      mode: global
      resources:
        limits:
          memory: 256m

  logstash:
    <<: *replicated
    image: docker.elastic.co/logstash/logstash:${ELASTIC_STACK_VERSION}
    labels:
      co.elastic.logs/enabled: "true"
    configs:
      - source: logstash-config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash-pipeline-config
        target: /usr/share/logstash/config/logstash.conf
      - source: logstash-pipelines
        target: /usr/share/logstash/config/pipelines.yml
    secrets:
      - source: elastic-ca-certificate
        target: /etc/logstash/config/certs/ca.crt
    volumes:
      - logstash:/usr/share/logstash/data
    networks:
      operational:
        aliases:
          - logstash.elastic
    environment:
      LOGSTASH_USER: elastic
      LOGSTASH_PASSWORD: ${ELASTIC_PASSWORD}
    deploy:
      placement:
        constraints: [node.role == manager]
