#log all dns queries
log-queries
#use google as default nameservers
server=8.8.4.4
server=8.8.8.8
server=1.1.1.1
#explicitly define host-ip mappings
address=/bookkk.me/10.8.0.2
cname=www.bookkk.me, bookkk.me
cname=orchestrator.bookkk.me, bookkk.me
cname=kafka.bookkk.me, bookkk.me
cname=kibana.bookkk.me, bookkk.me
cname=vpn.bookkk.me, bookkk.me