version: "3.9"

networks:
  operational:
    external: true

volumes:
  kafka_1_volume:
    driver: local
  kafka_2_volume:
    driver: local
  kafka_3_volume:
    driver: local
  elastic_1_volume:
    driver: local
  logstash_volume:
    driver: local

x-templates:
  replicated-deploy: &replicated
    logging:
      options:
        max-size: 20m
        max-file: 5
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

services:
  kafka-1:
    <<: *replicated
    image: bitnami/kafka:3.8.0
    networks:
      operational:
        aliases:
          - first.kafka
    volumes:
      - kafka_1_volume:/bitnami/kafka
    environment:
      # KRaft
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_KRAFT_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@first.kafka:${KAFKA_CONTROLLER_PORT},2@second.kafka:${KAFKA_CONTROLLER_PORT},3@third.kafka:${KAFKA_CONTROLLER_PORT}
      # Listeners
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_LISTENERS: CONTROLLER://:${KAFKA_CONTROLLER_PORT},PLAINTEXT://:${KAFKA_BROKER_PORT}
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      # Config
      KAFKA_CFG_NUM_PARTITIONS: 3
      # Clustering
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 2
    # Swarm
    deploy:
      placement:
        constraints: [node.role == worker]

  kafka-2:
    <<: *replicated
    image: bitnami/kafka:3.8.0
    networks:
      operational:
        aliases:
          - second.kafka
    volumes:
      - kafka_2_volume:/bitnami/kafka
    environment:
      # KRaft
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_KRAFT_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@first.kafka:${KAFKA_CONTROLLER_PORT},2@second.kafka:${KAFKA_CONTROLLER_PORT},3@third.kafka:${KAFKA_CONTROLLER_PORT}
      # Listeners
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_LISTENERS: CONTROLLER://:${KAFKA_CONTROLLER_PORT},PLAINTEXT://:${KAFKA_BROKER_PORT}
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      # Config
      KAFKA_CFG_NUM_PARTITIONS: 3
      # Clustering
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 2
    #    swarm
    deploy:
      placement:
        constraints: [node.role == worker]

  kafka-3:
    <<: *replicated
    image: bitnami/kafka:3.8.0
    networks:
      operational:
        aliases:
          - third.kafka
    volumes:
      - kafka_3_volume:/bitnami/kafka
    environment:
      # KRaft
      KAFKA_CFG_NODE_ID: 3
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_KRAFT_CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@first.kafka:${KAFKA_CONTROLLER_PORT},2@second.kafka:${KAFKA_CONTROLLER_PORT},3@third.kafka:${KAFKA_CONTROLLER_PORT}
      # Listeners
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CFG_LISTENERS: CONTROLLER://:${KAFKA_CONTROLLER_PORT},PLAINTEXT://:${KAFKA_BROKER_PORT}
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      # Config
      KAFKA_CFG_NUM_PARTITIONS: 3
      # Clustering
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 2
    # swarm
    deploy:
      placement:
        constraints: [node.role == worker]

  kafka-ui:
    <<: *replicated
    image: provectuslabs/kafka-ui:latest
    networks:
      operational:
        aliases:
          - ui.kafka
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: first.kafka:9092
      KAFKA_CLUSTERS_0_NAME: ${KAFKA_CLUSTER_ID}
      AUTH_TYPE: "LOGIN_FORM"
      SPRING_SECURITY_USER_NAME: ${KAFKA_UI_USERNAME}
      SPRING_SECURITY_USER_PASSWORD: ${KAFKA_UI_PASSWORD}
    # swarm
    deploy:
      placement:
        constraints: [node.role == manager]