worker_processes auto;
events {
}
http {
  ssl_session_cache   shared:SSL:10m;
  ssl_session_timeout 10m;

  resolver 127.0.0.11 valid=60s;

  server {
    listen              80;
    server_name         identity.localhost;

    add_header Strict-Transport-Security "max-age=63072000" always;

    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host  $host;
    proxy_set_header X-Forwarded-Port  $server_port;

    location / {
      set $upstream keycloak;
      proxy_pass http://$upstream:8080;
    }
  }

  server {
    listen              80;
    server_name         localhost;

    location /api/auth {
        set $upstream auth.service;
        proxy_pass http://$upstream:80;
    }
    location /api/user {
        set $upstream user.service;
        proxy_pass http://$upstream:80;
    }
    location /api/business {
        set $upstream business.service;
        proxy_pass http://$upstream:80;
    }
    location /api/appointment {
        set $upstream appointments.service;
        proxy_pass http://$upstream:80;
    }
  }
}