input {
    beats {
        port => 5045
    }
}
filter {
}
output {
    elasticsearch {
        hosts => ["https://master1.elastic.bookk.me:9200", "https://master2.elastic.bookk.me:9200", "https://master3.elastic.bookk.me:9200"]
        ssl_certificate_authorities => ["/etc/logstash/config/certs/ca.crt"]
        ssl => true
        user => "${LOGSTASH_USER}"
        password => "${LOGSTASH_PASSWORD}"
    }
    stdout { codec => rubydebug }
}