org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true

-Djavax.net.ssl.trustStore=/Users/antiufieievmichael/IdeaProjects/bookk-server/keystore.p12 -Djavax.net.ssl.keyStore=/Users/antiufieievmichael/IdeaProjects/bookk-server/keystore.p12 -Djavax.net.ssl.trustStorePassword=6485 -Djavax.net.ssl.keyStorePassword=6485

#Kotlin
kotlin.code.style=official
