worker_processes auto;
events {
}
http {
  ssl_session_cache   shared:SSL:10m;
  ssl_session_timeout 10m;

  resolver 127.0.0.11 valid=30s;

  server {
    listen 443 ssl;
    server_name         orchestrator.bookkk.me;
    access_log  off;
    http2  on;
    ssl_certificate     /etc/letsencrypt/live/bookkk.me-0001/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bookkk.me-0001/privkey.pem;
    allow 10.8.0.0/24;
    deny all;

    location / {
        set $upstream orchestrator.bookk.me;
        proxy_pass https://$upstream:9443;
    }
  }

  server {
    listen 443 ssl;
    server_name         admin.bookkk.me;
    access_log  off;
    ssl_certificate     /etc/letsencrypt/live/bookkk.me-0001/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bookkk.me-0001/privkey.pem;
    allow 10.8.0.0/24;
    deny all;

    location / {
        set $upstream admin.bookk.me;
        proxy_pass http://$upstream:8080;
    }
  }

  server {
    listen 443 ssl;
    server_name         kafka.bookkk.me;
    ssl_certificate     /etc/letsencrypt/live/bookkk.me-0001/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bookkk.me-0001/privkey.pem;
    allow 10.8.0.0/24;
    deny all;

    location / {
        set $upstream ui.kafka.bookk.me;
        proxy_pass http://$upstream:8080;
    }
  }

  server {
    listen 443 ssl;
    server_name         kibana.bookkk.me;
    access_log  off;
    ssl_certificate     /etc/letsencrypt/live/bookkk.me-0001/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bookkk.me-0001/privkey.pem;
    allow 10.8.0.0/24;
    deny all;

    location / {
        set $upstream kibana.elastic.bookk.me;
        proxy_pass http://$upstream:5601;
    }
  }

  server {
    listen 443 ssl;
    server_name         vpn.bookkk.me;
    access_log  off;
    ssl_certificate     /etc/letsencrypt/live/bookkk.me-0001/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bookkk.me-0001/privkey.pem;

    location / {
        set $upstream vpn.bookk.me;
        proxy_pass http://$upstream:51821;
    }
  }

  server {
    listen 443 ssl;
    server_name         bookkk.me www.bookkk.me;
    ssl_certificate     /etc/letsencrypt/live/bookkk.me-0001/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bookkk.me-0001/privkey.pem;

    location = /.well-known/apple-app-site-association {
       default_type application/json;
       alias /srv/static/ios_well_known.json;
    }
    location = /.well-known/assetlinks.json {
       default_type application/json;
       alias /srv/static/android_well_known.json;
    }
    location /api/auth {
        set $upstream authorization.service.bookk.me;
        proxy_pass https://$upstream;
    }
    location /api/user {
        set $upstream user.service.bookk.me;
        proxy_pass https://$upstream;
    }
  }

  server {
      listen      443 ssl default_server;
      server_name any.bookkk.me;
      return      444;
  }
}