[versions]
apache-common-pool = "2.4.3"
boringssl = "2.0.65.Final"
coroutines = "1.10.2"
flyway = "11.11.2"
hikari = "5.1.0"
kafka = "3.8.0"
koin-bom = "4.1.0"
kotlin = "2.2.0"
kotlin-datetime = "0.7.1"
ktor = "3.2.3"
ktor-doc = "4.0.3"
logback = "1.5.6"
mariadb-r2dbc = "1.3.0"
mariadb-jdbc = "3.4.1"
redis = "6.4.0.RELEASE"
passkey = "2.5.4"
exposed = "1.0.0-rc-1"
idempotency = "0.2.0"
mockk = "1.13.6"
money = "2.0.2"

[libraries]
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-mysql = { module = "org.flywaydb:flyway-mysql", version.ref = "flyway" }
hikari-cp = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
kafka-client = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-ktor = { module = "io.insert-koin:koin-ktor" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-reactive = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactive", version.ref = "coroutines" }
kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlin-datetime" }
kotlin-std = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version = "1.9.0" }
ktor-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-certificates = { module = "io.ktor:ktor-network-tls-certificates", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-client-log = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-documentation-generation = { module = "io.bkbn:kompendium-core", version.ref = "ktor-doc" }
ktor-documentation-generation-resources = { module = "io.bkbn:kompendium-resources", version.ref = "ktor-doc" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
ktor-logging = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
ktor-logging-call = { module = "io.ktor:ktor-server-call-logging", version.ref = "logback" }
ktor-server-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-client-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-plugin = { module = "io.ktor.plugin:io.ktor.plugin.gradle.plugin", version.ref = "ktor" }
ktor-protobuf = { module = "io.ktor:ktor-serialization-kotlinx-protobuf", version.ref = "ktor" }
ktor-server-resources = { module = "io.ktor:ktor-server-resources", version.ref = "ktor" }
ktor-client-resources = { module = "io.ktor:ktor-client-resources", version.ref = "ktor" }
ktor-test = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
ktor-status = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
ktor-idempotency = { module = "com.wolt:ktor-idempotency", version.ref = "idempotency" }
mariadb-r2dbc = { module = "org.mariadb:r2dbc-mariadb", version.ref = "mariadb-r2dbc" }
mariadb-jdbc = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariadb-jdbc" }
netty-boringssl = { module = "io.netty:netty-tcnative-boringssl-static", version.ref = "boringssl" }
redis-client = { module = "io.lettuce:lettuce-core", version.ref = "redis" }
redis-pool = { module = "org.apache.commons:commons-pool2", version.ref = "apache-common-pool" }
passkey = { module = "com.yubico:webauthn-server-core", version.ref = "passkey" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-r2dbc = { module = "org.jetbrains.exposed:exposed-r2dbc", version.ref = "exposed" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
exposed-migration = { module = "org.jetbrains.exposed:exposed-migration-core", version.ref = "exposed" }
exposed-migration-r2dbc = { module = "org.jetbrains.exposed:exposed-migration-r2dbc", version.ref = "exposed" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
joda-money = { module = "org.joda:joda-money", version.ref = "money" }


[plugins]
bookk-data = { id = "com.bookk.data" }
bookk-domain-api = { id = "com.bookk.domain.api" }
bookk-domain-impl = { id = "com.bookk.domain.impl" }
bookk-microservice = { id = "com.bookk.microservice" }
bookk-client = { id = "com.bookk.client" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-fixtures = { id = "java-test-fixtures" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }