version: "3.9"

networks:
  operational:
    external: true

secrets:
  private-jwt:
    external: true
  public-jwt:
    external: true
  ssl-keystore:
    external: true

volumes:
  database_volume:
    driver: local
  redis_data:
    driver: local

services:
  database:
    image: mariadb:11.5.2-ubi9
    networks:
      operational:
        aliases:
          - ${APPLICATION_SERVICE_NAME}.database
    environment:
      MARIADB_ROOT_PASSWORD: ${APPLICATION_DB_PASSWORD}
      MARIADB_DATABASE: ${APPLICATION_SERVICE_NAME}
      MARIADB_USER: ${APPLICATION_DB_USER}
      MARIADB_PASSWORD: ${APPLICATION_DB_PASSWORD}
      MYSQL_TCP_PORT: ${APPLICATION_DB_PORT}
    volumes:
      - database_volume:/var/lib/mysql
    logging:
      options:
        max-size: 20m
        max-file: 5
    deploy:
      placement:
        constraints: [ node.role == worker ]
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  redis:
    image: bitnami/redis:6.2.14
    volumes:
      - redis_data:/opt/bitnami/redis/

    networks:
      operational:
        aliases:
          - ${APPLICATION_SERVICE_NAME}.redis

    environment:
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL,CONFIG
      REDIS_PASSWORD: ${APPLICATION_REDIS_PASSWORD}

    deploy:
      placement:
        constraints: [ node.role == worker ]
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  microservice:
    image: ${APPLICATION_SERVICE_IMAGE}:${APPLICATION_SERVICE_VERSION}
    networks:
      operational:
        aliases:
          - ${APPLICATION_SERVICE_NAME}.service

    secrets:
      - source: public-jwt
        target: ${APPLICATION_JWT_PUBLIC_KEY_FILE}
      - source: private-jwt
        target: ${APPLICATION_JWT_PRIVATE_KEY_FILE}
      - source: ssl-keystore
        target: ${APPLICATION_SERVICE_SSL_FILE}
    env_file: "microservice.env"
    environment:
      APPLICATION_SERVICE_VERSION: ${APPLICATION_SERVICE_VERSION}
    logging:
      options:
        max-size: 100m
        max-file: 5
    deploy:
      placement:
        constraints: [ node.role == worker ]
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s