input {
    beats {
        port => 5045
    }
}
filter {
    grok {
        match => { "message" => "%{TIMESTAMP_ISO8601:time} \[%{LOGLEVEL:logLevel}%{SPACE}\] \[%{DATA:microservice}:%{DATA:microservice_version}\] \[%{DATA:source}\]: %{GREEDYDATA:message}"}
    }
}
output {
    elasticsearch {
        hosts => ["https://master1.elastic:9200", "https://master2.elastic:9200", "https://master3.elastic:9200"]
        ssl_certificate_authorities => ["/etc/logstash/config/certs/ca.crt"]
        ssl => true
        user => "${LOGSTASH_USER}"
        password => "${LOGSTASH_PASSWORD}"
    }
    stdout { codec => rubydebug }
}