version: "3.9"

networks:
  bookk-me:
    driver: overlay
    external: true

secrets:
  private-jwt:
    external: true
  public-jwt:
    external: true
  ssl-keystore:
    external: true

volumes:
  database_volume:
    driver: local
  redis_data:
    driver: local

services:
  database:
    image: mariadb:11.5.2-ubi9
    networks:
      bookk-me:
        aliases:
          - ${BOOKK_ME_SERVICE_NAME}.database.bookk.me
    environment:
      MARIADB_ROOT_PASSWORD: ${BOOKK_ME_DB_PASSWORD}
      MARIADB_DATABASE: ${BOOKK_ME_SERVICE_NAME}
      MARIADB_USER: ${BOOKK_ME_DB_USER}
      MARIADB_PASSWORD: ${BOOKK_ME_DB_PASSWORD}
      MYSQL_TCP_PORT: ${BOOKK_ME_DB_PORT}
    volumes:
      - database_volume:/var/lib/mysql

    deploy:
      placement:
        constraints: [ node.role == worker ]
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  redis:
    image: bitnami/redis:6.2.14
    volumes:
      - redis_data:/opt/bitnami/redis/

    networks:
      bookk-me:
        aliases:
          - ${BOOKK_ME_SERVICE_NAME}.redis.bookk.me

    environment:
      REDIS_DISABLE_COMMANDS: FLUSHDB,FLUSHALL,CONFIG
      REDIS_PASSWORD: ${BOOKK_ME_REDIS_PASSWORD}

    deploy:
      placement:
        constraints: [ node.role == worker ]
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  microservice:
    image: ${BOOKK_ME_SERVICE_IMAGE}:${BOOKK_ME_SERVICE_VERSION}
    networks:
      bookk-me:
        aliases:
          - ${BOOKK_ME_SERVICE_NAME}.service.bookk.me

    secrets:
      - source: public-jwt
        target: ${BOOKK_ME_JWT_PUBLIC_KEY_FILE}
      - source: private-jwt
        target: ${BOOKK_ME_JWT_PRIVATE_KEY_FILE}
      - source: ssl-keystore
        target: ${BOOKK_ME_SERVICE_SSL_FILE}
    env_file: "microservice.env"
    deploy:
      placement:
        constraints: [ node.role == worker ]
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s