worker_processes auto;
events {
}
http {
  ssl_session_cache   shared:SSL:10m;
  ssl_session_timeout 10m;

  resolver 127.0.0.11 valid=60s;

  server {
    listen *:443 ssl default_server;
    http2  on;
    server_name         local.bookkk.me;
    ssl_certificate     /etc/service/local.bookkk.me.pem;
    ssl_certificate_key /etc/service/local.bookkk.me.private.pem;

    location /api/auth {
        set $upstream auth.service.bookk.me;
        proxy_pass https://$upstream:443;
    }
    location /api/user {
        set $upstream user.service.bookk.me;
        proxy_pass https://$upstream:443;
    }
    location /api/business {
        set $upstream business.service.bookk.me;
        proxy_pass https://$upstream:443;
    }
  }
}