worker_processes auto;
events {
}
http {
  ssl_session_cache   shared:SSL:10m;
  ssl_session_timeout 10m;

  server {
    listen 443 ssl http2 default_server;
    ssl_certificate     /etc/service/nginx-selfsigned.crt;
    ssl_certificate_key /etc/service/nginx-selfsigned.key;

    location /api/auth {
        resolver 127.0.0.11 valid=10s;
        set $upstream auth.service.bookk.me;
        proxy_pass https://$upstream:443;
    }
    location /api/user {
        resolver 127.0.0.11 valid=10s;
        set $upstream user.service.bookk.me;
        proxy_pass https://$upstream:443;
    }
  }
}