volumes:
  docker-runner:
    driver: local

services:
  github-runner:
    image: myoung34/github-runner:2.320.0
    volumes:
      - docker-runner:/tmp/runner
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      RUN_AS_ROOT: "true"
      RUNNER_NAME: backend-runner
      ACCESS_TOKEN: ${RUNNER_ACCESS_TOKEN}
      RUNNER_WORKDIR: /tmp/runner/work
      RUNNER_SCOPE: 'repo'
      REPO_URL: "https://github.com/an22/bookk.me-backend"

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == worker ]