---
openapi: "3.1.0"
info:
  title: "UserMicroservice"
  description: "User operations"
  version: "0.0.1"
paths:
  /user:
    post:
      summary: "Get user by login and password."
      responses:
        "200":
          description: "User associated with provided credentials"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.book.user.domain.api.entity.User"
        "404":
          description: "User not found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/com.book.core.service.enity.SimpleServerError"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/com.book.user.domain.api.entity.Credentials"
components:
  schemas:
    com.book.core.service.enity.SimpleServerError:
      type: "object"
      properties:
        errorCode:
          type: "integer"
        message:
          type: "string"
      required:
      - "message"
      - "errorCode"
    com.book.user.domain.api.entity.Credentials:
      type: "object"
      properties:
        login:
          type: "string"
        password:
          type: "string"
      required:
      - "login"
      - "password"
    com.book.user.domain.api.entity.User:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        passwordHash:
          type: "string"
      required:
      - "id"
      - "name"
      - "passwordHash"
