version: "3.9"

services:
  service-auth:
    image: com.bookk.server.microservice.authorization
    hostname: auth.service
    ports:
      - '8000:8000'
    env_file:
      - service/auth.env
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -ea"
      TZ: "UTC"
    volumes:
      - './security/test.jks:/etc/service/keystore.jks:ro'
      - './security/private.pem:/etc/service/private.pem:ro'
      - './security/public.pem:/etc/service/public.pem:ro'

  service-user:
    image: com.bookk.server.microservice.user
    hostname: user.service
    ports:
      - '8001:8000'
    env_file:
      - service/user.env
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n -ea"
      TZ: "UTC"
    volumes:
      - './security/test.jks:/etc/service/keystore.jks:ro'
      - './security/private.pem:/etc/service/private.pem:ro'
      - './security/public.pem:/etc/service/public.pem:ro'

  service-business:
    image: com.bookk.server.microservice.business
    hostname: business.service
    ports:
      - '8002:8000'
    env_file:
      - service/business.env
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n -ea"
      TZ: "UTC"
    volumes:
      - './security/test.jks:/etc/service/keystore.jks:ro'
      - './security/private.pem:/etc/service/private.pem:ro'
      - './security/public.pem:/etc/service/public.pem:ro'

  service-appointments:
    image: com.bookk.server.microservice.appointments
    hostname: appointments.service
    ports:
      - '8003:8000'
    env_file:
      - service/appointments.env
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n -ea"
      TZ: "UTC"
    volumes:
      - './security/test.jks:/etc/service/keystore.jks:ro'
      - './security/private.pem:/etc/service/private.pem:ro'
      - './security/public.pem:/etc/service/public.pem:ro'