worker_processes auto;
events {
}
http {
  ssl_session_cache   shared:SSL:10m;
  ssl_session_timeout 10m;

  resolver 127.0.0.11 valid=60s;

  server {
    listen              80;
    server_name         localhost;

    location /api/auth {
        set $upstream auth.service;
        proxy_pass http://$upstream:80;
    }
    location /api/user {
        set $upstream user.service;
        proxy_pass http://$upstream:80;
    }
    location /api/business {
        set $upstream business.service;
        proxy_pass http://$upstream:80;
    }
    location /api/appointment {
        set $upstream appointments.service;
        proxy_pass http://$upstream:80;
    }
  }
}