package com.bookk.business.domain.api.error

object BusinessErrorCodes {
    private const val BASE = 200000

    const val BUSINESS_ALREADY_EXIST = BASE + 1
    const val BUSINESS_NAME_VALIDATION_ERROR = BASE + 2
    const val BUSINESS_NOT_FOUND = BASE + 3

    const val BUSINESS_CLIENT_EXISTS = BASE + 4
    const val BUSINESS_CLIENT_NAME_VALIDATION_ERROR = BASE + 5
    const val BUSINESS_CLIENT_NOT_EXISTS = BASE + 6

    const val BUSINESS_SERVICE_EXISTS = BASE + 7
    const val BUSINESS_SERVICE_NAME_VALIDATION_ERROR = BASE + 8
    const val BUSINESS_SERVICE_NOT_EXISTS = BASE + 9

    const val BUSINESS_SERVICE_GROUP_EXISTS = BASE + 10
    const val BUSINESS_SERVICE_GROUP_VALIDATION_ERROR = BASE + 11
    const val BUSINESS_SERVICE_GROUP_NOT_EXISTS = BASE + 12

    const val BUSINESS_QUOTE_SERVICE_NOT_FOUND = BASE + 13
    const val BUSINESS_QUOTE_EMPTY_SERVICE_LIST = BASE + 14

    const val BUSINESS_EMPLOYEE_INVITATION_EXISTS = BASE + 15
    const val BUSINESS_EMPLOYEE_INVITATION_VALIDATION_ERROR = BASE + 16
    const val BUSINESS_EMPLOYEE_INVITATION_ALREADY_PROCESSED = BASE + 17
    const val BUSINESS_EMPLOYEE_EXISTS = BASE + 18

    const val BUSINESS_ACTIVE_DAY_WITHOUT_WORK_HOURS = BASE + 19
    const val BUSINESS_INVALID_DAY_OFF_RANGE = BASE + 20

    const val BUSINESS_EMPLOYEE_VALIDATION_ERROR = BASE + 21
    const val BUSINESS_EMPLOYEE_ACTIVE_DAY_WITHOUT_WORK_HOURS = BASE + 22
    const val BUSINESS_EMPLOYEE_INVALID_DAY_OFF_RANGE = BASE + 23

    const val BUSINESS_EMPLOYEE_NOT_EXISTS = BASE + 24

    const val BUSINESS_CLIENT_MISSING_CONTACT_INFO = BASE + 25
}