name: Publish auth service
on:
  push:
    tags:
      - 'auth/*'

jobs:
  publish:
    name: Publish Auth Microservice
    uses: ./.github/workflows/service-publish-template.yml
    secrets:
      gradleEncryption: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
    with:
      module: "service:authorization:microservice"
      serviceName: "com.bookk.server.microservice.authorization"

  deploy:
    needs: publish
    name: Deploy Auth Microservice
    uses: ./.github/workflows/service-deploy-template.yml
    secrets:
      envFile: ${{ secrets.AUTH_ENV_FILE }}
      privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
      remoteUri: ${{ secrets.SWARM_MANAGER }}
      knownHosts: ${{ secrets.SSH_KNOWN_HOSTS }}
    with:
      image: "ghcr.io/an22/com.bookk.server.microservice.authorization"
      stackName: "authorization"
      version: ${{ needs.publish.outputs.version }}
