name: Publish services
on: workflow_dispatch

jobs:
  publish_auth_microservice:
    name: Publish Auth Microservice
    uses: ./.github/workflows/service-publish-template.yml
    with:
      module: "service:authorization:microservice"
      serviceName: "com.bookk.server.microservice.authorization"

  publish_user_microservice:
    name: Publish User Microservice
    uses: ./.github/workflows/service-publish-template.yml
    with:
      module: "service:user:microservice"
      serviceName: "com.bookk.server.microservice.user"