name: Service deploy template

on:
  workflow_call:
    secrets:
      envFile:
        required: true
      privateKey:
        required: true
      knownHosts:
        required: true
      remoteUri:
        required: true
    inputs:
      image:
        required: true
        type: string
      stackName:
        required: true
        type: string
      version:
        required: true
        type: string
      extension:
        required: false
        type: string

jobs:
  deployService:
    name: Deploy service
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Import environment variables from a secret
        shell: bash
        run: |
          env_variables='${{ secrets.envFile }}'
          without_blanks=${env_variables//[[:blank:]]/}
          echo "${without_blanks}" >> $GITHUB_ENV
          echo "${without_blanks}" >> "deployment/prod/microservice/microservice.env"

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.privateKey }}
          known_hosts: ${{ secrets.knownHosts }}
          if_key_exists: replace

      - name: Add remote context
        id: docker_context
        shell: bash
        run: |
          docker context create --docker "host=ssh://${{secrets.remoteUri}}" remote
          docker context use remote

      - name: Deploy without extension file
        if: ${{ inputs.extension == '' }}
        shell: bash
        env:
          APPLICATION_SERVICE_VERSION: ${{ inputs.version }}
          APPLICATION_SERVICE_IMAGE: ${{ inputs.image }}
        run: |
          cd deployment/prod/microservice
          docker stack deploy --prune --with-registry-auth --resolve-image=always --compose-file microservice-container-compose.yml ${{ inputs.stackName }}

      - name: Deploy with extension file
        if: ${{ inputs.extension != '' }}
        shell: bash
        env:
          APPLICATION_SERVICE_VERSION: ${{ inputs.version }}
          APPLICATION_SERVICE_IMAGE: ${{ inputs.image }}
        run: |
          cd deployment/prod/microservice
          docker stack deploy --prune --with-registry-auth --resolve-image=always --compose-file microservice-container-compose.yml --compose-file ${{ inputs.extension }} ${{ inputs.stackName }}


      - name: Remove remote context
        if: steps.docker_context.outcome == 'success'
        shell: bash
        run: docker context rm -f remote