name: Publish user service
on:
  push:
    tags:
      - 'user/*'

jobs:
  publish:
    name: Publish User Microservice
    uses: ./.github/workflows/service-publish-template.yml
    secrets:
      gradleEncryption: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
    with:
      module: "service:user:microservice"
      serviceName: "com.bookk.server.microservice.user"

  deploy:
    needs: publish
    name: Deploy User Microservice
    uses: ./.github/workflows/service-deploy-template.yml
    secrets:
      envFile: ${{ secrets.USER_ENV_FILE }}
      privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
      remoteUri: ${{ secrets.SWARM_MANAGER }}
      knownHosts: ${{ secrets.SSH_KNOWN_HOSTS }}
    with:
      image: "ghcr.io/an22/com.bookk.server.microservice.user"
      stackName: "user"
      version: ${{ needs.publish.outputs.version }}

