name: Publish user service
on:
  push:
    tags:
      - 'user/*'

jobs:
  publish_user_microservice:
    name: Publish User Microservice
    uses: ./.github/workflows/service-publish-template.yml
    with:
      registry: "ghcr.io/an22/"
      module: "service:user:microservice"
      serviceName: "com.bookk.server.microservice.user"
      envFile: ${{ secrets.USER_ENV_FILE }}
      tagPrefix: "user"
